### ISSUE TITLE
打包错误

### ISSUE THREAD

**Issue by threetown** [livegbs/GB28181-Server#17]
* 打包
`npm run build`

```bash
ERROR in ./node_modules/_css-loader@0.28.11@css-loader!./node_modules/_sass-loader@7.0.1@sass-loader/lib/loader.js!./assets/styles/element-custom.scss
Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
    at Object.sassLoader (D:\leon\labs\boss\GB28181-Server\web_src\node_modules\_sass-loader@7.0.1@sass-loader\lib\loader.js:31:19)
 @ ./assets/styles/element-custom.scss 4:14-171
 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./components/Play.vue
 @ ./components/Play.vue
 @ ./play.js
 @ multi babel-polyfill ./play.js

ERROR in ./assets/styles/element-custom.scss
Module build failed: ModuleBuildError: Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
    at Object.sassLoader (D:\leon\labs\boss\GB28181-Server\web_src\node_modules\_sass-loader@7.0.1@sass-loader\lib\loader.js:31:19)
    at D:\leon\labs\boss\GB28181-Server\web_src\node_modules\_webpack@3.6.0@webpack\lib\NormalModule.js:195:19
    at D:\leon\labs\boss\GB28181-Server\web_src\node_modules\_loader-runner@2.4.0@loader-runner\lib\LoaderRunner.js:367:11
    at D:\leon\labs\boss\GB28181-Server\web_src\node_modules\_loader-runner@2.4.0@loader-runner\lib\LoaderRunner.js:233:18
    at runSyncOrAsync (D:\leon\labs\boss\GB28181-Server\web_src\node_modules\_loader-runner@2.4.0@loader-runner\lib\LoaderRunner.js:143:3)
    at iterateNormalLoaders (D:\leon\labs\boss\GB28181-Server\web_src\node_modules\_loader-runner@2.4.0@loader-runner\lib\LoaderRunner.js:232:2)
    at D:\leon\labs\boss\GB28181-Server\web_src\node_modules\_loader-runner@2.4.0@loader-runner\lib\LoaderRunner.js:205:4
    at D:\leon\labs\boss\GB28181-Server\web_src\node_modules\_enhanced-resolve@3.4.1@enhanced-resolve\lib\CachedInputFileSystem.js:70:14
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

ERROR in js/index.b66c5ec9.js from UglifyJs
Unexpected token: name (result) [js/index.b66c5ec9.js:23600,6]

ERROR in js/login.3996dda0.js from UglifyJs
Unexpected token: name (result) [js/login.3996dda0.js:13286,6]
Child html-webpack-plugin for "index.html":
     1 asset
Child html-webpack-plugin for "login.html":
     1 asset
Child html-webpack-plugin for "play.html":
     1 asset
Child extract-text-webpack-plugin node_modules/_extract-text-webpack-plugin@3.0.1@extract-text-webpack-plugin/dist node_modules/_css-loader@0.28.11@css-loader/index.js!node_modules/_sass-loader@7.0.1@sass-loader/lib/loader.js!assets/styles/element-custom.scss:

    ERROR in ./node_modules/_css-loader@0.28.11@css-loader!./node_modules/_sass-loader@7.0.1@sass-loader/lib/loader.js!./assets/styles/element-custom.scss
    Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
        at Object.sassLoader (D:\leon\labs\boss\GB28181-Server\web_src\node_modules\_sass-loader@7.0.1@sass-loader\lib\loader.js:31:19)
Child extract-text-webpack-plugin node_modules/_extract-text-webpack-plugin@3.0.1@extract-text-webpack-plugin/dist node_modules/_css-loader@0.28.11@css-loader/index.js!node_modules/_font-awesome@4.7.0@font-awesome/css/font-awesome.css:
     5 assets
Child extract-text-webpack-plugin node_modules/_extract-text-webpack-plugin@3.0.1@extract-text-webpack-plugin/dist node_modules/_css-loader@0.28.11@css-loader/index.js!node_modules/_bootstrap@3.3.7@bootstrap/dist/css/bootstrap.css:
     5 assets
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by penggy** [comment]
npm install --registry=https://registry.npm.taobao.org
